name: Marine-Leisure

services:

  db:
    image: mysql:8.0
    networks:
      - marine-net
    container_name: marine_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: marine
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/your-org/your-repo:latest  # 최신 이미지 태그
    networks:
      - marine-net
    container_name: marine_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

volumes:
  db_data:

networks:
  marine-net:
    driver: bridge